### ISSUE TITLE
Missing transactions?

### ISSUE THREAD

**Issue by chmod** [bloxbean/cardano-client-lib#104]
I am kinda new to this, so if i do something wrong please let me know:

```
backendService.getAddressService().getTransactions("<RECEIVE_ADDR>",100,1, OrderEnum.desc)
        .getValue()
```
gives 19 transactions back, whilst ccvalut reports 25.

I am using 0.2.0-beta3 version

**Comment by satran004** [comment]
@chmod I tried with an address. It works for me.

You can verify the total transaction count for the address in cardanoscan.io


Can you please check in ccvault if the additional 6 transactions belong to another address at a different index ? Usually, wallet uses addresses at different indices for the same account.

If you want to simulate that in your java code, then you need to fetch transaction separately for address at each index.

**Comment by chmod** [comment]
Thanks. Using cardanoscan.io i found out that my wallet doesnt have just one address, but plenty. 🤯 Is there some way one can take all addresses given the stake hash?
