### ISSUE TITLE
MetadataHelper logs error on checkLength for CID V1 IPFS URI

### ISSUE THREAD

**Issue by woofpool** [bloxbean/cardano-client-lib#105]
I am using Nft.storage as my IPFS backend, which uses CID V1 standard instead of CID V0.

When running the code below, I see an error message coming from MetadataHelper.  The total bytes of my URI is 66, which is 2 bytes too many. 

Based on my research, it's not reliable to convert from CID V1 (base32) to CID V0 (base58), although nft.storage says it can be done.  

However, it surprises me that CIP25 would not cater for CID V1 URIs, if the limit is 64 bytes.  In my research, I could not see where CIP25 defines this limit, btw.  

Do you know of a work-around for this or do I need to pursue converting from CID V1 to CID V0?

Thanks!

Error
```
com.bloxbean.cardano.client.metadata.cbor.MetadataHelper: Strings in metadata must be at most 64 bytes when UTF-8 encoded. >> ipfs://bafkreidnqnosork5n7cm2ff5cdvew6f6fxum5hozbaheg6i6sa5cjdlel4
```

Code
```
static final String IPFS_URL_FORMAT = "ipfs://%s";
NFT nft = NFT.create()
                    .assetName(encodedUtf8AssetName)
                    .name(ipfsAsset.getFileName())
                    .image(String.format(IPFS_URL_FORMAT, ipfsAsset.getCid()));
```

**Comment by satran004** [comment]
@woofpool AFAIK, the limit is in  Cardano's metadata support "String must be 64 bytes".  

Please check this
https://developers.cardano.org/docs/get-started/cardano-serialization-lib/transaction-metadata/#metadata-limitations

Here's the link to CDDL https://github.com/input-output-hk/cardano-ledger/blob/1db68a3ec0a2dcb5751004beb22b906162474f23/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L323

To confirm,  can you please try the same with Javascript library?

**Comment by woofpool** [comment]
I appreciate the quick response!  

Based on this answer from Andrew Westberg, [stack-exchange-post](https://cardano.stackexchange.com/a/2574/326), I'm just going to split the URI into 2 parts and set the images property as a list of size 2.
```
NFT nft = NFT.create()
                .assetName(encodedUtf8AssetName)
                .name(ipfsAsset.getFileName());
nft.setImages(getImageUriList(String.format(IPFS_URL_FORMAT, ipfsAsset.getCid())));

List<String> getImageUriList(String imageUri) {
        int half = imageUri.length() / 2;
        return Arrays.asList(imageUri.substring(0, half), imageUri.substring(half));
}
```

**Comment by woofpool** [comment]
Closing issue.  Thanks much for your help, Satya.
