### ISSUE TITLE
Babbage Era - New Utxo fields inlineDatum, referenceScriptHash in Utxo (For Koios Backend)

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#131]
There are two new fields added to utxo in Babbage era to support inline datum and script reference. The Utxo class has already been updated with two new fields

```
private String inlineDatum;
private String referenceScriptHash;
``` 

Update Koios backend module to include these new fields in the response.

**Note:** please refer to Blockfrost backend impl change

**Comment by satran004** [comment]
fyi @edridudi

**Comment by edridudi** [comment]
Duplicate of #148
