### ISSUE TITLE
Koios Backend: Babbage era new fields for Utxo are missing 

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#148]
Koios backend's UtxoService impl needs to populate following new fields in Utxo class

1. inlineDatum
2. referenceScriptHash

**Comment by satran004** [comment]
fyi. @edridudi

**Comment by edridudi** [comment]
Is it related to this https://github.com/cardano-community/guild-operators/pull/1466 ?

**Comment by satran004** [comment]
> Is it related to this [cardano-community/guild-operators#1466](https://github.com/cardano-community/guild-operators/pull/1466) ?

It seems we may need to use tx_info endpoint.

**Comment by edridudi** [comment]
We can fill models by using multiple endpoints but I don't think that it is smart performance wise.

**Comment by edridudi** [comment]
To Be Fixed in Koios Java Client 1.14
