### ISSUE TITLE
Token Burning

### ISSUE THREAD

**Issue by MSchiavi** [bloxbean/cardano-client-lib#195]
Is there any update on burning tokens? I saw an older issue and this [example](https://github.com/bloxbean/cardano-client-examples/blob/135f54b50dd807afc2fcbda1c7c95d57a2c564c3/src/main/java/com/bloxbean/cardano/client/examples/MintAndBurn.java) that this isn't available with the high level mint api. 

The example seems out of date and some of the methods are deprecated now.

**Comment by satran004** [comment]
@MSchiavi There is no high level api available for burn token.

The easiest way is to use "composable functions" with some manual tx object transformation.
 Here's an example how to do that. 

I think we can introduce a high level composable function for burn token to hide the burn specific manual transformation in the example. I will try to add that in the next release. 

But for now the following example should work

https://github.com/bloxbean/cardano-client-examples/blob/dae2011af0ad2226df2629a7b91c997257d8ac64/src/test/java/com/bloxbean/cardano/client/example/function/minting/MintAndBurnTokenTest.java#L91

**Comment by MSchiavi** [comment]
Thanks for the reply @satran004 this worked and I appreciate you writing out a specific example. Great stuff.
