### ISSUE TITLE
Issue when trying to clone the repository

### ISSUE THREAD

**Issue by zoltanferenczfi** [bloxbean/cardano-client-lib#2]
Cloning into 'C:\Users\zolta\OneDrive\Documents\GitHub\cardano-client-lib'...
remote: Enumerating objects: 1478, done.        
remote: Counting objects: 100% (1444/1444), done.        
remote: Compressing objects: 100% (652/652), done.        
remote: Total 1478 (delta 567), reused 1206 (delta 357), pack-reused 34        
Receiving objects: 100% (1478/1478), 298.95 KiB | 1023.00 KiB/s, done.
Resolving deltas: 100% (567/567), done.
Submodule 'cardano-serialization-lib' (https://github.com/bloxbean/cardano-serialization-lib.git) registered for path 'cardano-serialization-lib'
Cloning into 'C:/Users/zolta/OneDrive/Documents/GitHub/cardano-client-lib/cardano-serialization-lib'...
remote: Enumerating objects: 1416, done.        
remote: Counting objects: 100% (271/271), done.        
remote: Compressing objects: 100% (214/214), done.        
remote: Total 1416 (delta 169), reused 97 (delta 57), pack-reused 1145        
Receiving objects: 100% (1416/1416), 685.37 KiB | 1.98 MiB/s, done.
Resolving deltas: 100% (891/891), done.
**fatal: reference is not a tree: 8c0f517ec39c333369462659b6c350223619973b
Unable to checkout '8c0f517ec39c333369462659b6c350223619973b' in submodule path 'cardano-serialization-lib'**

Would you like to retry cloning ?

**Comment by satran004** [comment]
It's working for me. Can you please try again.

```
bash-3.2$ 
bash-3.2$ git clone https://github.com/bloxbean/cardano-client-lib.git
Cloning into 'cardano-client-lib'...
remote: Enumerating objects: 1556, done.
remote: Counting objects: 100% (1522/1522), done.
remote: Compressing objects: 100% (684/684), done.
remote: Total 1556 (delta 599), reused 1271 (delta 376), pack-reused 34
Receiving objects: 100% (1556/1556), 316.60 KiB | 17.59 MiB/s, done.
Resolving deltas: 100% (599/599), done.
bash-3.2$ cd cardano-client-lib/
bash-3.2$ git submodule update --init --recursive
Submodule 'cardano-serialization-lib' (https://github.com/bloxbean/cardano-serialization-lib.git) registered for path 'cardano-serialization-lib'
Cloning into '/Users/satya/work/release/cardano-client-lib/cardano-serialization-lib'...
Submodule path 'cardano-serialization-lib': checked out '8c0f517ec39c333369462659b6c350223619973b'
Submodule 'binaryen' (git@github.com:WebAssembly/binaryen.git) registered for path 'cardano-serialization-lib/binaryen'
Cloning into '/Users/satya/work/release/cardano-client-lib/cardano-serialization-lib/binaryen'...
Submodule path 'cardano-serialization-lib/binaryen': checked out '547e2be14d1f8f9b21905baee87b1946045b0fe7'
bash-3.2$ 
bash-3.2$ 
```

**Comment by zoltanferenczfi** [comment]
Well, what I did was: I downloaded the full repository from GitHub as ZIP and placed it into the very same directory to where I tried to clone and then asked GitHub Desktop just to sync and since then it seems to be fine.

I have successfully built it for Windows,I have a small correction for you guys: the "build-windows-x86_64.bat" file inside the "scripts" folder needs a "cd .." to the very first line.

**Comment by satran004** [comment]
Good to know that it's working now.

The script needs to be executed from the project's root folder.  That's how the current CI scripts are configured. So we may not need cd ..
