### ISSUE TITLE
Natural order for keys in Map serialisation / deserialisation [PlutusData]

### ISSUE THREAD

**Issue by matiwinnetou** [bloxbean/cardano-client-lib#229]
Current serialisation of maps in DefaultPlutusObjectConverter is causing issues between offchain and onchain compatibility. Natural order of keys is not preserved leading to situations where comparing maps using equals operator fails despite the fact that those maps have exactly the same keys and values (but in different order).

Sorting on chain is rather a silly option so we should solve this properly in the offchain code.

Maps are serialised on chain according to a natural order, since in keys are bytearrays at the end of the day we need to provide such an implementation that will either automatically serialise maps according to a natural order or will let developer specify the order that will match on chain.

One solution that I tried for this was simply forcing all datum classes which are keys in map to be carried on-chain to implement Comparable. This doesn't work for multiple reason but one reason is when taking data from on chain and deserialising off-chain we don't know the order anyway.

I reached the conclusion that the only way to implement this is that all PlutusData types extend / implement Comparable in cardano-client-library according to natural order.

Work is rather easy but a bit time consuming only but this is the only way to giver developers ability to pass maps via redeemers both on and off chain.

Currently we have the following classes that implement PlutusData:

- BigIntPlutusData
- BytesPlutusData
- ConstrPlutusData
- ListPlutusData
- MapPlutusData

Turns out Plutus doesn't support maps natively YET but only list of tuples but it makes sense to discuss this topic as a vendor specific extension.

I will be working on a CPS to address problem of native Map support in Plutus.

**Comment by matiwinnetou** [comment]
My proposal is to have something like

```
@PlutusField(serialiseAs=AscendingList | Map)
private SortedMap someField;
```

Default will be AscendingList (effectively list of tuples) because this is the only thing that Plutus supports for now but the reason I put Map option there is because this is vendor specific extension (Aiken) to have Maps serialised in a key natural order (ascending). Such a vendor extension means one does not need to convert List of tuples on chain to a Map (lower cpu cost).

**Comment by satran004** [comment]
According to the ledger spec, the keys in a Plutus data's CBOR map should be in canonical order. However, in some scenarios, the byte array sorting algorithm used in the CBOR library does not work as expected.

The root cause is that the compare function in the following code snippet compares signed bytes. This needs to be changed to unsigned byte comparison to obtain a similar result as Aiken.

```
TreeMap<byte[], byte[]> sortedMap = new TreeMap<>(new Comparator<byte[]>() {

            @Override
            public int compare(byte[] o1, byte[] o2) {
                if (o1.length < o2.length) {
                    return -1;
                }
                if (o1.length > o2.length) {
                    return 1;
                }
                for (int i = 0; i < o1.length; i++) {
                    if (o1[i] < o2[i]) {
                        return -1;
                    }
                    if (o1[i] > o2[i]) {
                        return 1;
                    }
                }
                return 0;
            }

        });
```
