### ISSUE TITLE
Duplicate class OSUtil

### ISSUE THREAD

**Issue by franrc** [bloxbean/cardano-client-lib#280]
Hi! I've an issue when I try to use the library on my android project. 

When I add the dependency :     

implementation("com.bloxbean.cardano:cardano-client-lib:0.4.3")

And build the project, I'm alway getting the same error: 

Duplicate class com.bloxbean.cardano.client.util.OSUtil found in modules jetified-cardano-client-common-0.4.3 (com.bloxbean.cardano:cardano-client-common:0.4.3) and jetified-cardano-client-core-0.4.3 (com.bloxbean.cardano:cardano-client-core:0.4.3)

I'have tried with 0.5.0-alpha.4 version as the problem persist. 

Do you know how I can fix the issue?

Thanks in advance

**Comment by satran004** [comment]
Thanks @franrc for reporting this issue.

 I think this issue was introduced during 0.4.x release, but was unnoticed as  it doesn't happen for a regular setup.

I have removed the duplicate class from core module and pushed the snapshot build to snapshot repository.
Can you please verify it ? 

You need to use **0.5.0-alpha.5-SNAPSHOT**

For snapshot repository configuration, please check here https://github.com/bloxbean/cardano-client-lib#for-snapshot-binaries

**Comment by franrc** [comment]
Thanks for the response @satran004, I have tested with the 0.5.0-alpha.5-SNAPSHOT and there is another error regarding repeated files: 

2 files found with path 'placeholder.txt'.
Adding a packagingOptions block may help, please refer to
https://developer.android.com/reference/tools/gradle-api/8.1/com/android/build/api/dsl/ResourcesPackagingOptions
for more information 

This files are in these two projects at the same path :
/cardano-client-quicktx
/cardano-client-backend

I don't know if those files must be placed at the same path, however it can be fix adding this code in gradle (Kotlin DSL) : 

    packaging {
        resources.merges.add("placeholder.txt")
    }

I'm gonna test the library in Android project, if I find anything else, I will let you know.

Thank you !

**Comment by satran004** [comment]
Thanks @franrc

I have removed unnecessary placeholder.txt files and pushed a new snapshot.

Let me know if you find any other issue. Also feel free to create PR.

Thanks a lot for testing for Android.

**Comment by franrc** [comment]
Hi again!

When are you planning to make an alpha version for this?

Having a snapshot I get unforeseen errors when it was working previously :(

Now I'm having this error: 

 java.lang.NoSuchMethodError: No static method compareUnsigned([B[B)I in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /apex/com.android.art/javalib/core-oj.jar)

Best regards and thanks

**Comment by satran004** [comment]
My plan was to move to beta once docs are ready, but I can publish an alpha version if that helps.

Regarding NoSuchMethodError, I am not sure why ``compareUnSigned`` is not there in Android Java. It's part of standard jdk since Java 9. I will check if it can be replaced with another method.

Thanks

**Comment by franrc** [comment]
Yeah, It should be compatible but this method, when I try to use It in my project, Android Studio says that It can be used from Android API 33 (Android 13).

I would appreciate if you can help me using another compatible method.

Thanks a lot!

**Comment by satran004** [comment]
@franrc I've made some updates and replaced ``compareUnSigned`` with Guava's implementation. I've done some preliminary testing with a basic Android app for account generation and a simple transaction, and everything appears to be working on my end. But,  my experience with Android is quite limited.

I've pushed a new snapshot release. Would you be able to give it a try and provide any feedback?

**Comment by franrc** [comment]
Hi @satran004 ! 

I have checked it in my app and now it's working properly :)

For Android users, they have to add the desugaring support library, there are other java8 methods from the library that we can't use in the app.

https://developer.android.com/studio/write/java8-support

Many thanks!

It's a very good job :)

**Comment by satran004** [comment]
Thanks @franrc
