### ISSUE TITLE
0.4.3  Path parameter "number" value must not be null. (parameter #2)

### ISSUE THREAD

**Issue by BlockByteMath** [bloxbean/cardano-client-lib#287]
Exception in thread "main" java.lang.IllegalArgumentException: Path parameter "number" value must not be null. (parameter #2)

**Comment by satran004** [comment]
@BlockByteMath Can you please add the full stack trace here? 

FYI, the high-level API in library is going to be deprecated in 0.5.0. If this is not existing code, you should use the Composable function API. Here's a getting started guide https://cardano-client.dev/docs/gettingstarted/simple-transfer and you can find many examples in example repo.

If you are using 0.5.0-alpha.4, you can also try the new Quick Tx API which provides a simple and declarative API. You can find many examples in integration tests (https://github.com/bloxbean/cardano-client-lib/blob/master/quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java)

**Comment by BlockByteMath** [comment]
<dependency>
			<groupId>com.bloxbean.cardano</groupId>
			<artifactId>cardano-client-lib</artifactId>
			<version>0.1.5</version>
		</dependency>


I am using this version

**Comment by BlockByteMath** [comment]
> @BlockByteMath您可以在此处添加完整的堆栈跟踪吗？
> 
> 仅供参考，库中的高级 API 将在 0.5.0 中弃用。如果这不是现有代码，您应该使用可组合函数 API。这是入门指南https://cardano-client.dev/docs/gettingstarted/simple-transfer，您可以在示例存储库中找到许多示例。
> 
> 如果您使用的是 0.5.0-alpha.4，您还可以尝试新的 Quick Tx API，它提供了简单的声明式 API。您可以在集成测试中找到许多示例（https://github.com/bloxbean/cardano-client-lib/blob/master/quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java）

I am using this version

com.bloxbean.cardano cardano-client-lib 0.1.5

**Comment by BlockByteMath** [comment]
> @BlockByteMath您可以在此处添加完整的堆栈跟踪吗？
> 
> 仅供参考，库中的高级 API 将在 0.5.0 中弃用。如果这不是现有代码，您应该使用可组合函数 API。这是入门指南https://cardano-client.dev/docs/gettingstarted/simple-transfer，您可以在示例存储库中找到许多示例。
> 
> 如果您使用的是 0.5.0-alpha.4，您还可以尝试新的 Quick Tx API，它提供了简单的声明式 API。您可以在集成测试中找到许多示例（https://github.com/bloxbean/cardano-client-lib/blob/master/quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java）

The 0.4.3 version is also used, and this issue also occurs in cases on the official website

**Comment by BlockByteMath** [comment]
> 线程“main”中出现异常 java.lang.IllegalArgumentException：路径参数“number”值不能为 null。（参数#2）

  // Define expected Outputs
        Output output1 = Output.builder()
                .address(receiverAddress1)
                .assetName(LOVELACE)
                .qty(adaToLovelace(10))
                .build();
        Output output2 = Output.builder()
                .address(receiverAddress2)
                .assetName(LOVELACE)
                .qty(adaToLovelace(20))
                .build();
        // Create a CIP20 message metadata
        MessageMetadata metadata = MessageMetadata.create()
                .add("First transfer transaction");
        // Define TxBuilder
        TxBuilder txBuilder = output1.outputBuilder()
                .and(output2.outputBuilder())
                .buildInputs(createFromSender(senderAddress, senderAddress))
                .andThen(metadataProvider(metadata))
                .andThen(balanceTx(senderAddress, 1));

        UtxoSupplier utxoSupplier = new DefaultUtxoSupplier(backendService.getUtxoService());
        ProtocolParamsSupplier protocolParamsSupplier = new DefaultProtocolParamsSupplier(backendService.getEpochService());
        //Build and sign the transaction
        Transaction signedTransaction = TxBuilderContext.init(utxoSupplier, protocolParamsSupplier)
                .buildAndSign(txBuilder, signerFrom(senderAccount));
        //Submit the transaction
        Result<String> result = backendService.getTransactionService().submitTransaction(signedTransaction.serialize());
        System.out.println(result);
