### ISSUE TITLE
TransactionWitnessSet throws InvalidWitnessesUTXOW

### ISSUE THREAD

**Issue by dsoumis** [bloxbean/cardano-client-lib#29]
I am trying to implement a mint transaction with TransactionInput/TransactionOutput (low level).
Following these:
``` 
Keys keys = KeyGenUtil.generateKey();
VerificationKey vkey = keys.getVkey();
SecretKey skey = keys.getSkey();
ScriptPubkey scriptPubkey = ScriptPubkey.create(vkey);
transaction.setWitnessSet(TransactionWitnessSet.builder().nativeScripts(List.of(scriptPubkey)).build()); 
``` 
when the transaction gets submitted the response throws InvalidWitnessesUTXOW.

I have also tried without success:
``` 
VerificationKey vkey = VerificationKey.create(account.publicKeyBytes());
ScriptPubkey scriptPubkey = ScriptPubkey.create(vkey);
transaction.setWitnessSet(TransactionWitnessSet.builder().nativeScripts(List.of(scriptPubkey)).build());
```
when the transaction gets submitted the response throws NoWitness.

What's the proper way to set the transaction witness set?

**Comment by satran004** [comment]
@dsoumis Please check if you are signing the transaction with both script SecretKey and sender account.

You can refer to the below token burn example using low-level api. Minting transaction should be similar.

https://github.com/bloxbean/cardano-client-examples/blob/135f54b50dd807afc2fcbda1c7c95d57a2c564c3/src/main/java/com/bloxbean/cardano/client/examples/MintAndBurn.java#L124

**Comment by dsoumis** [comment]
Thanks for the quick response and thank you for your answer!
I was signing the transaction with both script SecretKey and sender account, but with your example I realised that I was not signing the transaction after the fee estimation, only before.
That solved the issue.
