### ISSUE TITLE
Asset Dto

### ISSUE THREAD

**Issue by kozer** [bloxbean/cardano-client-lib#30]
Hello! Nice work!
Is there is a reason you have commented out the metadata from Asset dto?
Is there any way to obtain them?
Thanks!

**Comment by satran004** [comment]
Hi @kozer, Initially the plan was to keep the backend api layer minimal, so only functionalities required to build transaction and post transaction are there. 

So if you want to fetch additional data, you need to go through provider api directly. For example, you can use blockfrost-java api to get asset metadata.
https://github.com/blockfrost/blockfrost-java

But as currently the lib is mostly used for NFT , I think it makes sense to expose fetching metadata through  existing AssetService.  I will try to add that in future release.

**Comment by kozer** [comment]
Thanks @satran004 !! Hope to include this soon!
