### ISSUE TITLE
cardano-client-lib 0.1.5   ADA transfer successful, token transfer failed

### ISSUE THREAD

**Issue by BlockByteMath** [bloxbean/cardano-client-lib#300]
PaymentTransaction paymentTransaction =
                PaymentTransaction.builder()
                        .sender(senderAccount)
                        .receiver(receiverAddress)
                        .amount(amount)
                        //.unit(CardanoConstants.LOVELACE)
                        .unit("d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458")
                        .build();
   
   
There is no problem transferring ADA main currency.
Transfer d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458 Token error reported
    
    
    
    
    [PaymentTransaction(unit=d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458, amount=10000)]
22:37:33.090 [main] DEBUG com.bloxbean.cardano.client.backend.api.helper.TransactionHelperService - {
  "body" : {
    "inputs" : [ {
      "transactionId" : "748326fa5b919c485ddbc93c94f0d9a000e4cbcd52d80dc44f71a38b551b2790",
      "index" : 1
    } ],
    "outputs" : [ {
      "address" : "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33",
      "value" : {
        "coin" : 168090,
        "multiAssets" : [ {
          "policyId" : "d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143",
          "assets" : [ {
            "name" : "0x414458",
            "value" : 10000
          } ]
        } ]
      }
    }, {
      "address" : "addr1q9d03mv8ty0apfxl3w93avamqafgmgnkjn59nd2djjvngmv96j2mprflqpw20jknesga2q6hnhgz6gyaarafjat56e5qwmh2y2",
      "value" : {
        "coin" : 2413032,
        "multiAssets" : [ {
          "policyId" : "d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143",
          "assets" : [ {
            "name" : "0x414458",
            "value" : 980000
          } ]
        } ]
      }
    } ],
    "fee" : 170000,
    "ttl" : 101149747,
    "mint" : null,
    "metadataHash" : null,
    "validityStartInterval" : 0
  },
  "witnessSet" : null,
  "metadata" : null
}
22:37:33.097 [main] DEBUG com.bloxbean.cardano.client.backend.api.helper.TransactionHelperService - Requests: 
[PaymentTransaction(unit=d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458, amount=10000)]
22:37:46.997 [main] DEBUG com.bloxbean.cardano.client.backend.api.helper.TransactionHelperService - {
  "body" : {
    "inputs" : [ {
      "transactionId" : "748326fa5b919c485ddbc93c94f0d9a000e4cbcd52d80dc44f71a38b551b2790",
      "index" : 1
    } ],
    "outputs" : [ {
      "address" : "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33",
      "value" : {
        "coin" : 168090,
        "multiAssets" : [ {
          "policyId" : "d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143",
          "assets" : [ {
            "name" : "0x414458",
            "value" : 10000
          } ]
        } ]
      }
    }, {
      "address" : "addr1q9d03mv8ty0apfxl3w93avamqafgmgnkjn59nd2djjvngmv96j2mprflqpw20jknesga2q6hnhgz6gyaarafjat56e5qwmh2y2",
      "value" : {
        "coin" : 2411327,
        "multiAssets" : [ {
          "policyId" : "d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143",
          "assets" : [ {
            "name" : "0x414458",
            "value" : 980000
          } ]
        } ]
      }
    } ],
    "fee" : 171705,
    "ttl" : 101149747,
    "mint" : null,
    "metadataHash" : null,
    "validityStartInterval" : 0
  },
  "witnessSet" : null,
  "metadata" : null
}
22:37:48.185 [main] ERROR com.bloxbean.cardano.client.backend.api.helper.TransactionHelperService - Trasaction submission failed
Transaction Failed: Result{successful=false, response='{"error":"Bad Request","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO [((Addr Mainnet (KeyHashObj (KeyHash \\\"a944e2ab4772053dc80ee8fed4b952a38e338a37f42c5d733e012a43\\\")) (StakeRefBase (KeyHashObj (KeyHash \\\"45065eea961918a1591cd736f7d5615bb6317c37127dec34a941a53f\\\"))),Value 168090 (fromList [(PolicyID {policyID = ScriptHash \\\"d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143\\\"},fromList [(414458,10000)])]),NoDatum,SNothing),Coin 1142150)]))])\"","status_code":400}', code=400, value=TransactionResult(signedTxn=[], transactionId=null)}

**Comment by BlockByteMath** [comment]
> 

BackendService backendService = new BFBackendService(
                Constants.BLOCKFROST_MAINNET_URL, "");

        FeeCalculationService feeCalculationService = backendService.getFeeCalculationService();

        TransactionHelperService transactionHelperService = backendService.getTransactionHelperService();
        BlockService blockService = backendService.getBlockService();

        String senderMnemonic = "";
        Account senderAccount = new Account(Networks.mainnet(), senderMnemonic);

        String receiverAddress = "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33";
        //BigInteger amount = BigInteger.valueOf(1344798).subtract(BigInteger.valueOf(193456));
        BigInteger amount = BigInteger.valueOf(20000);
        PaymentTransaction paymentTransaction =
                PaymentTransaction.builder()
                        .sender(senderAccount)
                        .receiver(receiverAddress)
                        .amount(amount)
                        //.unit(CardanoConstants.LOVELACE)
                        .unit("d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458")
                        .build();

        long ttl = blockService.getLastestBlock().getValue().getSlot() + 1000;

        TransactionDetailsParams detailsParams = TransactionDetailsParams.builder().ttl(ttl).build();
        //Calculate fee
        BigInteger fee = feeCalculationService.calculateFee(paymentTransaction,detailsParams, null);
        //Set fee
        //paymentTransaction.setFee(fee);
        paymentTransaction.setFee(BigInteger.valueOf(193456));

        Result<TransactionResult> result = transactionHelperService.transfer(paymentTransaction, detailsParams);
        if(result.isSuccessful()){
            System.out.println("Transaction Success: " + result.getValue().getTransactionId());
        }else{
            System.out.println("Transaction Failed: " + result);
        }

**Comment by BlockByteMath** [comment]
> > 
> 
> BackendService backendService = new BFBackendService( Constants.BLOCKFROST_MAINNET_URL, "");
> 
> ```
>     FeeCalculationService feeCalculationService = backendService.getFeeCalculationService();
> 
>     TransactionHelperService transactionHelperService = backendService.getTransactionHelperService();
>     BlockService blockService = backendService.getBlockService();
> 
>     String senderMnemonic = "";
>     Account senderAccount = new Account(Networks.mainnet(), senderMnemonic);
> 
>     String receiverAddress = "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33";
>     //BigInteger amount = BigInteger.valueOf(1344798).subtract(BigInteger.valueOf(193456));
>     BigInteger amount = BigInteger.valueOf(20000);
>     PaymentTransaction paymentTransaction =
>             PaymentTransaction.builder()
>                     .sender(senderAccount)
>                     .receiver(receiverAddress)
>                     .amount(amount)
>                     //.unit(CardanoConstants.LOVELACE)
>                     .unit("d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458")
>                     .build();
> 
>     long ttl = blockService.getLastestBlock().getValue().getSlot() + 1000;
> 
>     TransactionDetailsParams detailsParams = TransactionDetailsParams.builder().ttl(ttl).build();
>     //Calculate fee
>     BigInteger fee = feeCalculationService.calculateFee(paymentTransaction,detailsParams, null);
>     //Set fee
>     //paymentTransaction.setFee(fee);
>     paymentTransaction.setFee(BigInteger.valueOf(193456));
> 
>     Result<TransactionResult> result = transactionHelperService.transfer(paymentTransaction, detailsParams);
>     if(result.isSuccessful()){
>         System.out.println("Transaction Success: " + result.getValue().getTransactionId());
>     }else{
>         System.out.println("Transaction Failed: " + result);
>     }
> ```



> 

sender：
balance  ADA = 8   
ADX= d2175511c5793b09d27b7ddac0f64cc1b9900fe1dca1607ea949f143414458  balance =100

addr1q9d03mv8ty0apfxl3w93avamqafgmgnkjn59nd2djjvngmv96j2mprflqpw20jknesga2q6hnhgz6gyaarafjat56e5qwmh2y2

receiver:
addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33

**Comment by BlockByteMath** [comment]
> @BlockByteMath看起来输出之一没有足够的 ada 来满足最小 utxo 要求。
> 
> ```
> "address" : "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33",
> "value" : {
> "coin" : 168090
> ```
> 
> 您能告诉我在这次交易期间您在发件人地址上有多少 Ada 吗？另外，如果可能，请提供转账的示例代码。我会尝试重现它。
> 
> 顺便说一句，PaymentTransaction api（高级 api）在 0.5.0 中已弃用。您应该计划迁移到最新版本。:)

Hello, can you help me check the issues with this version

**Comment by BlockByteMath** [comment]
> @BlockByteMath Looks like one of the output doesn't have enough ada to meet min utxo requirement.
> 
> ```
> "address" : "addr1qx55fc4tgaeq20wgpm50a49e223cuvu2xl6zchtn8cqj5s69qe0w49serzs4j8xhxmma2c2mkcchcdcj0hkrf22p55ls6nmp33",
> "value" : {
> "coin" : 168090
> ```
> 
> Can you please let me know how much Ada you had at the sender address during this transaction? Also, if possible, please provide the sample code for the transfer. I will try to reproduce it.
> 
> Btw, PaymentTransaction api (High level api) is deprecated in 0.5.0. You should plan to move to the latest version. :)

Why do I still deduct 1.44 ADA when transferring DXD tokens in my wallet? How is PaymentTransaction implemented in the code?

**Comment by satran004** [comment]
@BlockByteMath I didn't get a chance to try out your code today. I will test it tomorrow.

Regarding ADA deducted during DXD token transfer, every UTXO/output requires a minimum ADA amount in the output. You can't transfer just a native token.

CCL tries to calculate the required minimum ADA automatically based on the defined standard. This mainly depends on a few protocol parameters and the number of tokens in the output. Since you are using a very old version of the library, the minimum ADA calculation might differ slightly. I recommend upgrading to a newer version, such as 0.4.3 or 0.5.0-beta1, to see if you encounter the same issue. The Transaction API should remain compatible, but you might notice a few package changes.

**Comment by BlockByteMath** [comment]
> @BlockByteMath我今天没有机会尝试你的代码。我明天会测试一下。
> 
> 关于DXD代币流通时的ADA，每个UTXO/输出都需要输出其中最低的ADA数量。您不能仅转移本机令牌。
> 
> CCL 尝试根据定义的标准自动计算所需的最低 ADA。这主要取决于一些协议参数和输出中的令牌数量。由于您使用非常旧版本的库，因此最小 ADA 计算可能会不同。我建议升级到较新的版本，例如0.4.3或0.5.0-beta1，看看您是否遇到同样的问题。事务API应保持兼容，但您可能会注意到一些包发生了更改。

Sorry, the project cannot be upgraded to a new version at the moment. How did you specify the output ADA code in the PaymentTransaction code in the old version when transferring DXD tokens? I don't see any code for this in the provided example

**Comment by satran004** [comment]
@BlockByteMath 

I think I've found the root cause. The calculated minimum ADA value for the UTXO is lower than the actual required value. This is why you are encountering the ``BabbageOutputTooSmallUtxo`` error.

If you check the [MinAdaCalculator.java](https://github.com/bloxbean/cardano-client-lib/blob/186fdac1da605d00a0e975c09be86917bd9c5fe8/src/main/java/com/bloxbean/cardano/client/common/MinAdaCalculator.java#L17), you'll see that it relies on a protocol parameter named ``coinsPerUtxoWord``

This field was renamed during the Alonzo era. Furthermore, its value was changed from 34482 to 4310 because the minimum ADA calculation now uses bytes instead of words in the current era (or post-Alonzo).

However, CCL 0.1.5 is not compatible with the current era. It still expects the old value of 34482, but it retrieves 4310 through protocol parameters. So, the calculated minimum ADA is insufficient.

You have two options now:

    1. You can try to override EpochService.getProtocolParameter() to return the expected value, ensuring that the MinAda calculation remains accurate.
    
    2.Consider upgrading the library to version 0.4.3.
    
Fyi, you can review the protocol parameter update history [here](https://beta.explorer.cardano.org/en/protocol-parameters/histories). Please scroll down and check the coinPerUtxoSize field. You'll notice how the value changed from the old figure in epoch 364.

**Comment by BlockByteMath** [comment]
> @BlockByteMath
> 
> I think I've found the root cause. The calculated minimum ADA value for the UTXO is lower than the actual required value. This is why you are encountering the `BabbageOutputTooSmallUtxo` error.
> 
> If you check the [MinAdaCalculator.java](https://github.com/bloxbean/cardano-client-lib/blob/186fdac1da605d00a0e975c09be86917bd9c5fe8/src/main/java/com/bloxbean/cardano/client/common/MinAdaCalculator.java#L17), you'll see that it relies on a protocol parameter named `coinsPerUtxoWord`
> 
> This field was renamed during the Alonzo era. Furthermore, its value was changed from 34482 to 4310 because the minimum ADA calculation now uses bytes instead of words in the current era (or post-Alonzo).
> 
> However, CCL 0.1.5 is not compatible with the current era. It still expects the old value of 34482, but it retrieves 4310 through protocol parameters. So, the calculated minimum ADA is insufficient.
> 
> You have two options now: 1. You can try to override EpochService.getProtocolParameter() to return the expected value, ensuring that the MinAda calculation remains accurate. 2.Consider upgrading the library to version 0.4.3.
> 
> Fyi, you can review the protocol parameter update history [here](https://beta.explorer.cardano.org/en/protocol-parameters/histories). Please scroll down and check the coinPerUtxoSize field. You'll notice how the value changed from the old figure in epoch 364.

Thank you. I'll give it a try
