### ISSUE TITLE
Koios: Transaction UTxOs is deprecated

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#326]
The following endpoint has been deprecated. 

https://api.koios.rest/api/v0/tx_utxos

**Comment by satran004** [comment]
@edridudi

**Comment by edridudi** [comment]
From Koios Devs:

> I think we jumped the gun on mainnet one to mention deprecated....part of upcoming changes on v1.1.0:
there will be new utxo_info endpoint, which will show utxo details against bulk tx requested and will be consistent in schema across address_utxos,account_utxos, asset_utxos
