### ISSUE TITLE
Please add JDK compile version information to your release notes

### ISSUE THREAD

**Issue by esodot** [bloxbean/cardano-client-lib#328]
Would be really helpful to have a release information for the compiled JDK version. 
We used the com.bloxbean.cardano:cardano-client-lib:0.5.0-beta1 and it was compiled with the JDK 17. Upgrading to the com.bloxbean.cardano:cardano-client-lib:0.5.0-beta3 (compiled with Major Version 63 JDK 19) the compilation is not possible until bumping to TARGET JDK 19. 
Thanks you :)

Hint:
In Android projects you have something like this in your project build file: 

`    compileOptions {
        // Sets Java compatibility to Java 17
        targetCompatibility JavaVersion.VERSION_17
        sourceCompatibility JavaVersion.VERSION_17
    }`

**Comment by satran004** [comment]
@esodot CCL is Java 11 compatible. You can check it here
https://github.com/bloxbean/cardano-client-lib/blob/86eba66195f6d58d87e3c52a4b569de37e89f482/build.gradle#L19

Java 11 is used for compilation. Let me check with a sample Android.

**Comment by esodot** [comment]
Thank you very much. It seems to be a strange issue on my side. Closing it
