### ISSUE TITLE
Wrong Data <=> CBOR encoding/decoding

### ISSUE THREAD

**Issue by nau** [bloxbean/cardano-client-lib#399]
In Cardano Plutus ALL bytestring MUST be chunked up to 64 bytes. This includes Plutus Data ByteString AND BigInteger represented as byte strings.

So default CBOR encodings are incorrect and can not be used.

Instead, we all MUST implement custom byte string handling, especially for BigIntegers like here: 
[decodeBoundedBigInteger](https://github.com/IntersectMBO/plutus/blob/441b76d9e9745dfedb2afc29920498bdf632f162/plutus-core/plutus-core/src/PlutusCore/Data.hs#L243)

**Comment by satran004** [comment]
@nau I am looking into this issue now.

Is it possible for you to provide some test data for this or point me to any available test cases?

**Comment by nau** [comment]
Here are a couple of test cases:

[DataCborCodecSpec](https://github.com/nau/scalus/blob/refactor/tests/shared/src/test/scala/scalus/builtin/DataCborCodecSpec.scala)

Please, take a look at
```scala
test("ByteString chunks")
```
and 
```scala
test("BigInt encoding/decoding of > 64 bits is chunked")
```

**Comment by satran004** [comment]
Thanks @nau
