### ISSUE TITLE
OgmiosEpochService getProtocolParams does not return some params

### ISSUE THREAD

**Issue by nemo83** [bloxbean/cardano-client-lib#424]
Not sure if it's an issue,

But 
```OgmiosEpochService ogmiosEpochService = new OgmiosEpochService("http://ryzen:31337");
        var ogmiosProtoParams = ogmiosEpochService.getProtocolParameters().getValue();```

Does not return all params, eg

`minFeeRefScriptCostPerByte=null`

This causes tx balancing to fail.

**Comment by satran004** [comment]
Thanks @nemo83. This is a bug. The minFeeRefScriptCostPerByte is currently missing in the Ogmios backend service implementation, as well as in Koios.

So, the reference script fee will only work with the Blockfrost backend in version 0.6.0-beta1.

**Workaround for now:**
You can manually set minFeeRefScriptCostPerByte=15 after retrieving the protocol parameters from the backend provider.

We will fix this in the next release.

**Comment by nemo83** [comment]
Thanks for confirming this. Let me know if you need any help in getting this done. I just wanted to be sure it was an actual issue (and not me mis-using the library)

**Comment by satran004** [comment]
I will fix this as part of the following PR as there is also a dependency with cost model

https://github.com/bloxbean/cardano-client-lib/pull/418

**Comment by nemo83** [comment]
> I will fix this as part of the following PR as there is also a dependency with cost model
> 
> #418

oh interesting, I thought there were issues w/ costs models too, but could not pin point to it. happy to hear you're on top of things! and thanks for fixing ogmios too.
