### ISSUE TITLE
How to properly decode a Cardano Bech32 address

### ISSUE THREAD

**Issue by YordanPavlov** [bloxbean/cardano-client-lib#43]
As described [here](https://cips.cardano.org/cips/cip19/):
"_By convention, Shelley and stake addresses are encoded using Bech32, with the exception that Cardano does not impose a length limit on the sequence of characters._".
And indeed there are addresses with length > 90 as [this one](https://cardanoscan.io/address/addr1qy0nx340mwwm6sfne95e0luts0p82rhqfjv8j2wt2dxa5eqnk9egqqful60vptswxu72q7ulvknsvzzae9n98p05kgxs43qvt2). What is the proper way to decode this address as the Bech32 implementation even in the _cardano-client-lib_ library has this check as seen [here](https://github.com/bloxbean/cardano-client-lib/blob/master/src/main/java/com/bloxbean/cardano/client/common/Bech32.java#L149)

**Comment by satran004** [comment]
@YordanPavlov You are right. 

The current Bech32 Java impl in cardano-client-lib is only used during asset's fingerprint calculation.
For address generation, lib is using cardano-serialization-lib's rust implementation through JNI.

Though there is a pull request to impl full Bech32 impl in Java, but it's not done yet. Need more focus. https://github.com/bloxbean/cardano-client-lib/pull/17

But you may want to refer to cardano-serialization-lib's rust impl to understand more about the implementation. Here's the link to source file

https://github.com/Emurgo/cardano-serialization-lib/blob/f64e95231443bda1e174cf7a58e57948a7a9cee1/rust/src/address.rs#L268

**Comment by satran004** [comment]
Address impl: https://github.com/bloxbean/cardano-client-lib/blob/master/src/main/java/com/bloxbean/cardano/client/address/AddressService.java

Bech 32 impl
https://github.com/bloxbean/cardano-client-lib/blob/master/src/main/java/com/bloxbean/cardano/client/crypto/Bech32.java
