### ISSUE TITLE
Add impl to generate child public key from parent public key when not hardened

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#46]

**Comment by zack-scott** [comment]
I have implemented some of the logic to start working on this, and I am getting the derivation for the chain code to come out correct. But, I am not having luck with getting the public key to come out correct. I am sure I am doing something wrong with the math somewhere.

`    /**
     * Derive the public child key from HD parent public key
     *
     * @param parent     the parent key
     * @param child      the child index
     * @return
     */
    public HdPublicKey getPublicChildKey(HdPublicKey parent, long child) {
        HdPublicKey publicKey = new HdPublicKey();

        byte[] childNumber = BytesUtil.ser32LE(child);


        publicKey.setVersion(parent.getVersion());
        publicKey.setDepth(parent.getDepth() + 1);
        publicKey.setChildNumber(childNumber);


        //If derivation V2 Shelley
        byte[] AP = parent.getKeyData();
        byte[] cP = parent.getChainCode();

        byte[] I;
    
        byte[] data = BytesUtil.merge(new byte[]{2}, AP, childNumber);
        byte[] IL = Arrays.copyOfRange(Hmac.hmac512(data, cP), 0, 28);
        
        data[0] = 3;
        I = Hmac.hmac512(data, cP);
        
        byte[] IR = Arrays.copyOfRange(I, 32, 64);
        publicKey.setChainCode(IR); // verified to be correct chain code




        BigInteger kLiBI = parseUnsignedLE(IL)
                .multiply(BigInteger.valueOf(8))
                .add(parseUnsignedLE(AP));
        BigInteger order = BigInteger.valueOf(2).pow(252)
                .add(new BigInteger("27742317777372353535851937790883648493"));
        if (kLiBI.mod(order).equals(BigInteger.ZERO)) {
            return null;
        }
        IL = serializeUnsignedLE256(kLiBI);

        byte[] A = ED25519SPEC.getB().scalarMultiply(IL).toByteArray();

        publicKey.setKeyData(A);



        return publicKey;
    }`

**Comment by satran004** [comment]
@zack-scott Thanks for trying this out. 

I had faced some issue while trying to implement this earlier. 
As I am traveling now, I have limited access to my laptop for next few days.
I will try to verify your impl with the spec next week.

**Comment by zack-scott** [comment]
@satran004  looking at the Math library and the implementation used along with the BIP32 docs. I believe to derive the public key from a public key you will need to do the scalarMultiply on IL and then add the Parent key data to the Group Element then convert back to a byte array. I have adjusted the code above to reflect that. Thank you for taking the time to respond.

**Comment by satran004** [comment]
@zack-scott Finally I am able to verify it. 

Please find the modified code below with a test.  Need some more tests.

Please feel free to create a PR after your verification.

I have done few changes. 
- For child public key, only 28 bytes taken for left side (ZL)
- For hmac512(), data should be with prefix 0x02 for child public key and with prefix 0x03 for child chain code calculation
- Some minor changes (variable renaming etc.)

Here's the link to the bip32-ed25519 spec. I am referring to section "D. Public child key". https://raw.githubusercontent.com/LedgerHQ/orakolo/master/papers/Ed25519_BIP%20Final.pdf

**Impl**
```
 public HdPublicKey getChildPublicKey(HdPublicKey parent, long child) {
        HdPublicKey publicKey = new HdPublicKey();
        byte[] AP = parent.getKeyData();

        byte[] pChain = parent.getChainCode();
        byte[] childNumber = BytesUtil.ser32(child);

        //prefix 0x02 for child public key
        byte[] ApLE = serializeUnsignedLE256(parseUnsignedLE(AP));
        byte[] data = BytesUtil.merge(new byte[]{2}, ApLE, BytesUtil.ser32LE(child));
        byte[] Z = Hmac.hmac512(data, pChain);

        //prefix 0x0c for child chain code
        data[0] = 3;
        byte[] c = Hmac.hmac512(data, parent.getChainCode());

        //truncate to right 32 bytes for child chain code
        c = Arrays.copyOfRange(c, 32, 64);

        // split into left (28 bytes) /right (for child public key)
        byte[] ZL = Arrays.copyOfRange(Z, 0, 28);
//      byte[] ZR = Arrays.copyOfRange(Z, 32, 64);

        //Ai ← AP + [8ZL]B,
        BigInteger kLiBI = parseUnsignedLE(ZL)
                .multiply(BigInteger.valueOf(8));

        byte[] kLi = serializeUnsignedLE256(kLiBI);

        GroupElement gp1 = new GroupElement(ED25519SPEC.getCurve(), AP);
        gp1 = gp1.toCached();
        GroupElement groupElement = ED25519SPEC.getB().scalarMultiply(kLi).add(gp1);
        //TODO -- If Ai is the identity point (0, 1), discard the child

        byte[] Ai = groupElement.toByteArray(); //child public key

        publicKey.setVersion(parent.getVersion());
        publicKey.setDepth(parent.getDepth() + 1);
        publicKey.setChildNumber(childNumber);
        publicKey.setChainCode(c);
        publicKey.setKeyData(Ai);

        return publicKey;
    }
```

**Test**

```
    @Test
    void testPubKeyFromParentPubKey() {
        String mnemonicPhrase = "indicate traffic belt syrup chief accident put upset present short drink bus glide warm roof";

        Account account = new Account(mnemonicPhrase,2);
        HdKeyPair hdKeyPair = account.hdKeyPair();
        HdKeyGenerator hdKeyGenerator = new HdKeyGenerator();
        HdKeyPair childHdKeyPair = hdKeyGenerator.getChildKeyPair(hdKeyPair, 1, false);

       HdPublicKey publicKey = hdKeyGenerator.getChildPublicKey(hdKeyPair.getPublicKey(), 1);

        assertThat(publicKey.getKeyData()).isEqualTo(childHdKeyPair.getPublicKey().getKeyData());
    }
```

**Comment by satran004** [comment]
@zack-scott fyi, I have created a separate issue to track identity point verification

 https://github.com/bloxbean/cardano-client-lib/issues/129
