### ISSUE TITLE
How to generate always abstain certification and sign?

### ISSUE THREAD

**Issue by HirotoShioi** [bloxbean/cardano-client-lib#477]
Hello, I was wondering if you can use the cardano client lib to generate `always-abstain` delegation certificate and sign it using cardano client lib? Thank you very much
https://developers.cardano.org/docs/get-started/cardano-cli/governance/delegate%20to%20a%20drep/?

**Comment by satran004** [comment]
@HirotoShioi You can use DRep.abstain() with QuickTx to do that. Here's a code snippet to register stake address and drep delegation in the same tx.

```
        Tx tx = new Tx()
                .registerStakeAddress(stakeAddr)
                .delegateVotingPowerTo(stakeAddr, DRep.abstain())
                .from(sender1Addr);

        Result<String> result = quickTxBuilder.compose(tx)
                .withSigner(SignerProviders.stakeKeySignerFrom(sender2))
                .withSigner(SignerProviders.signerFrom(sender1))
                .completeAndWait(s -> System.out.println(s));
```

**Comment by HirotoShioi** [comment]
@satran004 I see! Thank you very much for the quick response!
