### ISSUE TITLE
 @GET("addresses/{address}/txs") deprecated

### ISSUE THREAD

**Issue by CardaCardz** [bloxbean/cardano-client-lib#49]
@GET("addresses/{address}/txs")
 Is now deprecated, see the blockfrost documentation
![image](https://user-images.githubusercontent.com/95542143/146760642-92f581bf-7b3b-4d23-b48a-3ada57cdc649.png)

Instead we should use the 
@GET("addresses/{address}/transactions")
![image](https://user-images.githubusercontent.com/95542143/146760744-a98b40bc-e604-4cd6-be25-b172f4994c67.png)

**Comment by satran004** [comment]
@CardaCardz Thanks for the info. I will fix it in the next release.
