### ISSUE TITLE
Remove coin selection responsibility from the library and introduce a way to provide selected utxos in TransactionHelperService

### ISSUE THREAD

**Issue by satran004** [bloxbean/cardano-client-lib#5]
In the current implementation, the coin selection is done by UtxoTransactionBuilder (UtxoTransactionBuilderImpl). TransactionHelperService invokes buildTransaction / buildMintTokenTransaction methods of UtxoTransactionBuilder to get the final Transaction object which is sent to the Cardano node.

Though the current implementation of Utxo selection in UtxoTransactionBuilderImpl works for now, it may not be efficient or may not work in certain scenarios. The current implementation is very basic which goes through all the utxos in a asc/desc order and tries to select utxos for the transaction. 

The coin selection is a complex topic with different possible algorithms as mentioned in  this [CIP](https://cips.cardano.org/cips/cip2/)

**So the goal is to decouple coin(Utxo) selection from the  UtxoTransactionBuilder service. So a client application can provide selected utxos as part of PaymentTransaction / MintTransaction object.**

Possible solution
-----
1. Client application should be able run coin selection algorithm out side of this library and provide selected Utxos as part of PaymentTransaction or MintTransaction or any equivalent objects in future.
2. If a list of Utxos provided by the consumer, UtxoTransactionBuilder impl will create the final Transaction instance by creating TransactionInputs and TransactionOutputs.
3. UtxoTransactionBuilder may throw Insufficient balance exception if not enough value available in provided Utxos.
4. In case utxos list provided by the client is empty, UtxoTransactionBuilder impl will try to go through the current flow of finding Utxos. The current impl of coin selection will be  deprecated but will be there for some time as it provides a quick way to try the library without worrying about coin selection. But it will not be a recommended way.

**Comment by edridudi** [comment]
Some reference for future implementations:
[Coin Selection by Nami Wallet](https://github.com/Berry-Pool/nami-wallet/blob/main/src/lib/coinSelection.js)
[Coin Selection CIP-2](https://cips.cardano.org/cips/cip2/)
