### ISSUE TITLE
Please add "addresses/{address}/total" support

### ISSUE THREAD

**Issue by CardaCardz** [bloxbean/cardano-client-lib#50]
As far as I investigated, I have not found the implementation for the "addresses/{address}/total" support, bloxbean version 0.1.5.

I believe, that this addition will help users like me to get full information regarding address without a need to perform additional requests to the API.

Please kindly refer to the provided screenshot for more information.
![image](https://user-images.githubusercontent.com/95542143/146760994-cdae87aa-cf29-4a0d-b950-6024380160cc.png)

**Comment by CardaCardz** [comment]
Here is the only available methods for the Account part in library
![image](https://user-images.githubusercontent.com/95542143/146761575-d015811d-b512-4f66-b151-bf845fde1d95.png)

**Comment by satran004** [comment]
The current backend api layer has only the minimum apis required to post a transaction or any other operations supported by the library. Adding too many methods may increase the effort to implement any new backend.

For additional endpoints, you may want to use blockfrost-java library.

But I think you are right. We can add few commonly used apis to the backend api layer, even if those are not required by the library. May be we can annotate those additional  apis with an @Optional tag, so it's not mandatory to implement those additional apis in every backend implementation.
