### ISSUE TITLE
Account should be able to sign anything

### ISSUE THREAD

**Issue by somereason** [bloxbean/cardano-client-lib#51]
Account object can sign transaction hex string now. But when I try to sign some random hex string, an error reported:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeError { location: Some("Transaction"), failure: CBOR(Expected(Array, Map)) }', src/transaction.rs:14:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think account should be able to sign more than transactions. 
If I want to sign some thing to prove I'm the key owner, I can't do it now.
As far as I know, cardano serialization lib(in javascript) can do this job.

**Comment by satran004** [comment]
In  "0.2.0-preview2" (just released), you can sign any arbitrary message with SigningProvider.

You can get the instance of default signing provider through Configuration.getSigningProvider().

If you want to use Account to sign the message, you have to use ```signExtended()```

You can get privateKey and publicKey bytes from Account object and call this method.

Here's a test case for your reference 

https://github.com/bloxbean/cardano-client-lib/blob/3d85b52d4984af369457fb2628c3a507e23a40fa/src/test/java/com/bloxbean/cardano/client/crypto/api/impl/DefaultSigningProviderTest.java#L23

But, I think it makes sense to add a helper method in Account to sign any arbitrary message. I will do that in the next iteration.

**Comment by somereason** [comment]
Thank you, That's very helpful
