### ISSUE TITLE
Questions about script classes - uses / purpose

### ISSUE THREAD

**Issue by magick93** [bloxbean/cardano-client-lib#69]
Hello

Firstly, thanks for putting this library together. I have been following your tutorials and have successfully minted a token!

I have a few beginner questions that I'm hoping you can help with, or point me in the right direction.

Can you tell me, what are the following classes for? What would be a reason to use these?

- RequireTimeAfter
- RequireTimeBefore 
- ScriptAll
- ScriptAny 
- ScriptAtLeast

Thanks

**Comment by satran004** [comment]
@magick93 These classes are used to control the minting policy. Like  who can mint / burn a native asset and when.

ScriptAll, ScriptAny, ScriptAtLeast can be used to create multi-sig policy script. The policy id for the native  asset is generated from the script hash.

Similarly, RequireTimeAfter/Before can be used to create TimeLock script. That means you can only mint a native asset only before/after a certain slot number.

You can check this link for more details https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/simple-scripts.md#multi-signature-scripts

**Comment by satran004** [comment]
Closing this. Feel free to reopen it if required.
