### ISSUE TITLE
JsonNoSchemaToMetadataConverter::processValueNode doesn't properly handle DoubleNode

### ISSUE THREAD

**Issue by bkreiser** [bloxbean/cardano-client-lib#74]
I tried to convert some Json that had a double and it converts it to Integer. 

```
} else if(value instanceof NumericNode) {
            BigInteger valueInt = ((NumericNode)value).bigIntegerValue(); // For a DoubleNode type it just converts to an Int
            return valueInt;
} else {
```

**Comment by satran004** [comment]
Thanks @bkreiser 

Does metadata schema support double value ? If I remember correctly, it only supports int (both positive and negative values). Please check this page https://github.com/input-output-hk/cardano-node/blob/master/doc/reference/tx-metadata.md

I might be wrong. I will check in details again.

**Comment by bkreiser** [comment]
Perhaps your correct.  I was trying to implement the new standard for
Royalties (CIP-0027) and had assumed that the royalty percentage was to be
a double value but now that I look again they have it expressed as a string.

https://cardanoupdates.com/commits/d52e01804677cda7bc8fc828d0c2a09dbf1f584e

**Comment by satran004** [comment]
Closing this.

**Comment by bkreiser** [comment]
Thanks!
