### ISSUE TITLE
Check if minimum Ada is not met - issue

### ISSUE THREAD

**Issue by sourcelib-stack** [bloxbean/cardano-client-lib#79]
Hi,

In the _**UtxoTransactionBuilderImpl**.buildOuputsForSenderFromUtxos_ you have this check
`
//Check if minimum Ada is not met. Topup
//Transaction will fail if minimum ada not there. So try to get some additional utxos
verifyMinAdaInOutputAndUpdateIfRequired(transactionInputs, changeOutput, detailsParams, utxoSet, protocolParams);
`

this is not quite correct as the rule is : transaction should be min 1 ada and not the resulting UTOX in the wallet.

For example if I have 1.5 ada in a wallet and I want to transfer it this should be fine (1.5 - fee). the node will validate it.

**Comment by satran004** [comment]
Thanks.
>> this is not quite correct as the rule is : transaction should be min 1 ada and not the resulting UTOX in the wallet.

As per my understanding, resulting UTXO should have some min ada. Without multi-asset it is 1 ada.
Please check here https://docs.cardano.org/native-tokens/minimum-ada-value-requirement

>> For example if I have 1.5 ada in a wallet and I want to transfer it this should be fine (1.5 - fee). the node will validate it.
Yes node should validate that. In this case most probably there will be only 1 Utxo.

**Comment by sourcelib-stack** [comment]
Just to clarify a bit, the issue I'm signaling here is that with this condition there you cannot send all the ada from a wallet, it throws the error.

If I comment out the verifyMinAdaInOutputAndUpdateIfRequired works just fine.

**Comment by satran004** [comment]
Closing this. @sourcelib-stack  please re-open if you still see this issue.
