### ISSUE TITLE
the dependency can't support D start address And A start Address

### ISSUE THREAD

**Issue by malingzhao** [bloxbean/cardano-client-lib#8]

**Comment by satran004** [comment]
Can you please provide more details ?

**Comment by malingzhao** [comment]
String privateKey = "xprv1czpywutfnp84p3fwl322z76tl66v6mh93s95yxd7xumexnl04fyjpu5hdnuq2792e5fl282543ld209cgjhr2m7zdm87umyka8krmje0sexmhu5wln9cu3q9wpxmkseg47gup6sm0ruyg2hzmj2xxtwn2spkqpf8";
        String toAddress = "DdzFFzCqrhszg6cqZvDhEwUX7cZyNzdycAVpm4Uo2vjKMgTLrVqiVKi3MBt2tFAtDe7NkptK6TAhVkiYzhavmKV5hE79CWwJnPCJTREK";
        String fromAddress = "addr1q8kx3vtze86adr02m2k77s2nqjst8rhe0uqp3qln5t6c4y3rxwh76fzmrwef3lefl28lnnss22ahvre55sc6v9xt76gsp0f49t";
        BigDecimal amount = new BigDecimal("0.2");
        List<TransactionInput> inputList = new ArrayList<>();
        List<TransactionOutput> outputList = new ArrayList<>();
        Integer currentSlot = getCurrentSlotInfo();
        long ttl = currentSlot + 1000;

        int latestEpoch = getLatestEpoch();

**Comment by malingzhao** [comment]
同种类型的地址是可以进行转账的， 但是不同类型的话 发现是不能够进行转账的

**Comment by malingzhao** [comment]
how  to transfer from a shelly address to byron address

**Comment by satran004** [comment]
The current version of the library supports only Shelley address to Shelley address. 
I have not tested with Shelley to Byron address. Let me check and if possible I will plan to add it in future release.

**Comment by malingzhao** [comment]
Thank you very much ;

**Comment by satran004** [comment]
The root cause is Account.toBytes() fails for Byron address. Need to change this method to support Byron address. So a receiver can be a Byron address. Sender will always be a Shelley address while using this library.

Caused by: com.bloxbean.cardano.client.exception.AddressExcepion: Address to bytes failed
	at com.bloxbean.cardano.client.account.Account.toBytes(Account.java:188)
	at com.bloxbean.cardano.client.transaction.spec.TransactionOutput.serialize(TransactionOutput.java:26)

**Comment by malingzhao** [comment]
Thank you very mush , I will try again

**Comment by satran004** [comment]
@malingzhao I have pushed 0.1.3-beta to the maven central with this fix. Now you should be able to provide a Byron address as receiver. Sender is still shelley address only.
You may want to check your code with "0.1.3-beta". Let me know if the issue is still there.

**Comment by malingzhao** [comment]
Thank you very much / that is ok
