### ISSUE TITLE
Send arbitrary amount of $ada in multi asset minting tx

### ISSUE THREAD

**Issue by nemo83** [bloxbean/cardano-client-lib#9]
Hi! 

I'm a big fan of this library, that I've already used in two project live on mainnet.

I've been minting some NFT with the intructions at: https://github.com/bloxbean/cardano-client-lib#token-minting-transaction.

In particular I want to mint the token _directly_ into my recipents wallet.

Everything is working fine, but I do have an additional requirement, can I send more $ada in that tx?

Let's say I mint 1 token and instead of sending just 1.4 $ada (or thereabout) I want to directly send, let's say 10 $ada?

Is there a way I can do that? (is it even possible at blockchain level?)

Thanks 🙏

**Comment by satran004** [comment]
Thanks.

>> Let's say I mint 1 token and instead of sending just 1.4 $ada (or thereabout) I want to directly send, let's say 10 $ada?

This is an interesting usecase. Unfortunately,  the current high-level api (MintTransaction) doesn't have a "ada" value field.
Also, there is no high level api available to send both MintTransaction and PaymentTransaction in one transaction request.

Probably, a clean solution for future release :- Add a "value" field in MintTransaction to send any extra Ada in the mint transaction.

**For now you have two options:**

**Option 1:**
Use low level  apis like TransactionInput / TransactionOutput. But in that case, you have to select utxos and build the Transaction in your application. 

**Option 2**
Set min uxto value in TransactionDetailsParam to your required lovelace amount. Currently, default value is 1 Ada.
Pass the TransactionDetailsParam as part of mintToken().

**Note:** Currently, some extra ada value is getting added if you send a custom minAda. May be some unwanted side-effect due to change in min ada value in the client library which I need to debug.
But you can adjust the lovelace amount in TransactionDetailsParam based on your testing to avoid any extra ada value in the output.

Hope that helps.

Just wondering, if your project is public, would you be interested to add your project in the "Used By" section of this project.

```
MintTransaction paymentTransaction =
                MintTransaction.builder()
                        .sender(sender)
                        .receiver(receiver)
                        .mintAssets(Arrays.asList(multiAsset))
                        .policyScript(scriptPubkey)
                        .policyKeys(Arrays.asList(skey))
                        .build();

        TransactionDetailsParams detailsParams = TransactionDetailsParams.builder().ttl(getTtl()).build();
        detailsParams.setMinUtxoValue(new BigInteger("3000000"));

        BigInteger fee = feeCalculationService.calculateFee(paymentTransaction, detailsParams, metadata);
        paymentTransaction.setFee(fee);

        Result<TransactionResult> result = transactionHelperService.mintToken(paymentTransaction, detailsParams, metadata);
```

**Comment by nemo83** [comment]
Thanks for the quick answer.

I'll play around in testnet with the recommended workarounds.

Of course I can add the projects using the lib.

If that's ok, I'll keep this issue open and I'll report findings.

Are you planning to implemnt in java the cddl part? Or you'll be happy to rely on the native library?

Thanks again!

**Comment by satran004** [comment]
>> If that's ok, I'll keep this issue open and I'll report findings.

Yes. Let's keep it open.

>> Are you planning to implemnt in java the cddl part? Or you'll be happy to rely on the native library?
Cbor serialization is currently in pure Java only. 
The native library dependency is only for address generation and transaction signing. But I am planning to remove that dependency in future release. That will simplify current testing and build cycle :)

**Comment by nemo83** [comment]
> Thanks.
> 
> > > Let's say I mint 1 token and instead of sending just 1.4 $ada (or thereabout) I want to directly send, let's say 10 $ada?
> 
> This is an interesting usecase. Unfortunately, the current high-level api (MintTransaction) doesn't have a "ada" value field.
> Also, there is no high level api available to send both MintTransaction and PaymentTransaction in one transaction request.
> 
> Probably, a clean solution for future release :- Add a "value" field in MintTransaction to send any extra Ada in the mint transaction.
> 
> **For now you have two options:**
> 
> **Option 1:**
> Use low level apis like TransactionInput / TransactionOutput. But in that case, you have to select utxos and build the Transaction in your application and sign using the provided api.
> 
> **Option 2**
> Set min uxto value in TransactionDetailsParam to your required lovelace amount. Currently, default value is 1 Ada.
> Pass the TransactionDetailsParam as part of mintToken().
> 
> **Note:** Currently, some extra ada value is getting added if you send a custom minAda. May be some unwanted side-effect due to change in min ada value in the client library which I need to debug.
> But you can adjust the lovelace amount in TransactionDetailsParam based on your testing to avoid any extra ada value in the output.
> 
> Hope that helps.
> 
> Just wondering, if your project is public, would you be interested to add your project in the "Used By" section of this project.
> 
> ```
> MintTransaction paymentTransaction =
>                 MintTransaction.builder()
>                         .sender(sender)
>                         .receiver(receiver)
>                         .mintAssets(Arrays.asList(multiAsset))
>                         .policyScript(scriptPubkey)
>                         .policyKeys(Arrays.asList(skey))
>                         .build();
> 
>         TransactionDetailsParams detailsParams = TransactionDetailsParams.builder().ttl(getTtl()).build();
>         detailsParams.setMinUtxoValue(new BigInteger("3000000"));
> 
>         BigInteger fee = feeCalculationService.calculateFee(paymentTransaction, detailsParams, metadata);
>         paymentTransaction.setFee(fee);
> 
>         Result<TransactionResult> result = transactionHelperService.mintToken(paymentTransaction, detailsParams, metadata);
> ```

Suggestion number 1 seems to be working, but I can't seem to find a nice formula to map the desired amount to send to the minUtxo to set in the `TransactionDetailsParams`.

What I've found so far:
1. For 10 $ADA, minUtxo = 6.5
2. For 15 $ADA, minUtxo = 9.65
3. For 25 $ADA, minUtxo = 16.2

I'm happy to use this workaround, but I'm curious, if you know, where is the piece of code that is doing "weird" things, I might try to take a look. Thanks!

**Comment by satran004** [comment]
I have to still verify. But probably this behavior is expected as mentioned in the minAda calculation logic where minUtxo value is used. https://cardano-ledger.readthedocs.io/en/latest/explanations/min-utxo.html

If you want to check the implementation. you can check the following two files

MinAda calculation logic : https://github.com/bloxbean/cardano-client-lib/blob/85adffc45a2890228559e021fd16c14a4b3c3d9a/src/main/java/com/bloxbean/cardano/client/common/MinAdaCalculator.java#L9

Used here : https://github.com/bloxbean/cardano-client-lib/blob/85adffc45a2890228559e021fd16c14a4b3c3d9a/src/main/java/com/bloxbean/cardano/client/backend/api/helper/impl/UtxoTransactionBuilderImpl.java#L159

I will add the value attribute to MintTransaction in the next release,  then this workaround won't be required.

**Comment by nemo83** [comment]
> I will add the value attribute to MintTransaction in the next release, then this workaround won't be required.

<3
